trigger:
- main  # Runs pipeline when changes are pushed to 'main' branch

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self  # Ensures the repository is checked out

- task: AzureCLI@2
  displayName: 'Deploy Infrastructure using Bicep'
  inputs:
    azureSubscription: 'AzureServiceConnection'  # Replace with the correct name of your service connection
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Checking directory structure"
      ls -R  # Debugging step to verify file paths
      az group create --name econtracts-resource-group --location "East US"
      az deployment group create --resource-group econtracts-resource-group --template-file ./econtracts-azure-infra.bicep --parameters location="East US"
